import { useEffect, useMemo, useState } from "react";
import { ClipDetail } from "@/components/clips/clip-detail";
import { ClipGrid } from "@/components/clips/clip-grid";
import { ClipList } from "@/components/clips/clip-list";
import { ClipToolbar } from "@/components/clips/clip-toolbar";
import { Badge } from "@/components/ui/badge";
import { listClipsByFlow } from "@/lib/api";
import { cn } from "@/lib/utils";
import { useClipStore } from "@/stores/clip-store";
import type { Clip, FlowNodeKey } from "@/types";

type FlowClipsPanelProps = {
  flowId: number;
  selectedNode: FlowNodeKey | null;
  clipsCountHint?: number;
};

export function FlowClipsPanel({ flowId, selectedNode, clipsCountHint }: FlowClipsPanelProps) {
  const [flowClips, setFlowClips] = useState<Clip[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const activeClipId = useClipStore((s) => s.activeClipId);
  const setActiveClipId = useClipStore((s) => s.setActiveClipId);
  const viewMode = useClipStore((s) => s.viewMode);

  const loadClips = async () => {
    setLoading(true);
    setError(null);
    try {
      const next = await listClipsByFlow(flowId);
      setFlowClips(next);
    } catch (e) {
      setFlowClips([]);
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);

    void listClipsByFlow(flowId)
      .then((next) => {
        if (!cancelled) {
          setFlowClips(next);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          setFlowClips([]);
          setError(e instanceof Error ? e.message : String(e));
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
      setActiveClipId(null);
    };
  }, [flowId, setActiveClipId]);

  const flowClipIds = useMemo(() => new Set(flowClips.map((x) => x.id)), [flowClips]);
  const detailClipId = activeClipId != null && flowClipIds.has(activeClipId) ? activeClipId : null;
  const count = clipsCountHint ?? flowClips.length;
  const focused = selectedNode === "clip";

  return (
    <section
      className={cn(
        "app-panel-subtle space-y-3 rounded-2xl px-4 py-4",
        focused && "ring-1 ring-[rgba(85,179,255,0.35)]",
      )}
    >
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--color-text-muted)]">
            Clips
          </p>
          <p className="mt-1 text-sm text-[var(--color-text-muted)]">Flow-scoped clip review workspace.</p>
        </div>
        <div className="flex items-center gap-2">
          {focused ? <Badge variant="secondary">Selected node</Badge> : null}
          <Badge variant="outline">{count} total</Badge>
        </div>
      </div>

      {error ? <p className="text-sm text-[var(--color-primary)]">{error}</p> : null}

      {detailClipId != null ? (
        <ClipDetail clipId={detailClipId} onBack={() => setActiveClipId(null)} backLabel="Back to flow clips" />
      ) : (
        <>
          <ClipToolbar hideAccountFilter />
          {viewMode === "grid" ? (
            <ClipGrid
              clips={flowClips}
              loading={loading}
              onRefresh={loadClips}
              emptyMessage="No clips for this flow yet."
              queueTitle="Flow clip queue"
              queueDescription="Review clips generated by this flow."
            />
          ) : (
            <ClipList
              clips={flowClips}
              loading={loading}
              onRefresh={loadClips}
              emptyMessage="No clips for this flow yet."
            />
          )}
        </>
      )}
    </section>
  );
}
